import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Layout } from '@/components/mainLayout/MainLayout';
import './globals.css';
import { ReactNode } from 'react';
import { getLocale, getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import { AuthProvider } from '@/hooks/useAuth';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'APIQuest',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function LocaleLayout({ children }: Props) {
  const locale = await getLocale();
  const messages = await getMessages();
  const token = cookies().get('JWT')?.value || null;

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <AuthProvider initialToken={token}>
          <NextIntlClientProvider messages={messages}>
            <Layout>{children}</Layout>
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
